import { Action } from "./Controller";

export const noteControls = [
  // Toggles
  [Action.SceneToggle, 0],
  [Action.SceneToggle, 1],
  [Action.SceneToggle, 2],
  [Action.SceneToggle, 3],
  [Action.SceneToggle, 4],
  [Action.SceneToggle, 5],
  [Action.SceneToggle, 6],
  [Action.SceneToggle, 7],
  [Action.SceneToggle, 8],
  [Action.SceneToggle, 9],
  // Triggers
  [Action.SceneTrigger, 0, 0],
  [Action.SceneTrigger, 1, 0],
  [Action.SceneTrigger, 2, 0],
  [Action.SceneTrigger, 3, 0],
  [Action.SceneTrigger, 4, 0],
  [Action.SceneTrigger, 5, 0],
  [Action.SceneTrigger, 6, 0],
  [Action.SceneTrigger, 7, 0],
  [Action.SceneTrigger, 8, 0],
  [Action.SceneTrigger, 9, 0],
  [Action.SceneTrigger, 0, 1],
  [Action.SceneTrigger, 1, 1],
  [Action.SceneTrigger, 2, 1],
  [Action.SceneTrigger, 3, 1],
  [Action.SceneTrigger, 4, 1],
  [Action.SceneTrigger, 5, 1],
  [Action.SceneTrigger, 6, 1],
  [Action.SceneTrigger, 7, 1],
  [Action.SceneTrigger, 8, 1],
  [Action.SceneTrigger, 9, 1],
  [Action.SceneTrigger, 0, 2],
  [Action.SceneTrigger, 1, 2],
  [Action.SceneTrigger, 2, 2],
  [Action.SceneTrigger, 3, 2],
  [Action.SceneTrigger, 4, 2],
  [Action.SceneTrigger, 5, 2],
  [Action.SceneTrigger, 6, 2],
  [Action.SceneTrigger, 7, 2],
  [Action.SceneTrigger, 8, 2],
  [Action.SceneTrigger, 9, 2],
  // Toggles
  [Action.EffectToggle, 0],
  [Action.EffectToggle, 1],
  [Action.EffectToggle, 2],
  [Action.EffectToggle, 3],
  [Action.EffectToggle, 4],
  [Action.EffectToggle, 5],
  [Action.EffectToggle, 6],
  [Action.EffectToggle, 7],
  [Action.EffectToggle, 8],
  [Action.EffectToggle, 9],
  // Triggers
  [Action.EffectTrigger, 0, 0],
  [Action.EffectTrigger, 1, 0],
  [Action.EffectTrigger, 2, 0],
  [Action.EffectTrigger, 3, 0],
  [Action.EffectTrigger, 4, 0],
  [Action.EffectTrigger, 5, 0],
  [Action.EffectTrigger, 6, 0],
  [Action.EffectTrigger, 7, 0],
  [Action.EffectTrigger, 8, 0],
  [Action.EffectTrigger, 9, 0],
  [Action.EffectTrigger, 0, 1],
  [Action.EffectTrigger, 1, 1],
  [Action.EffectTrigger, 2, 1],
  [Action.EffectTrigger, 3, 1],
  [Action.EffectTrigger, 4, 1],
  [Action.SceneTrigger, 5, 1],
  [Action.SceneTrigger, 6, 1],
  [Action.SceneTrigger, 7, 1],
  [Action.SceneTrigger, 8, 1],
  [Action.SceneTrigger, 9, 1],
  [Action.SceneTrigger, 0, 2],
  [Action.SceneTrigger, 1, 2],
  [Action.SceneTrigger, 2, 2],
  [Action.SceneTrigger, 3, 2],
  [Action.SceneTrigger, 4, 2],
  [Action.SceneTrigger, 5, 2],
  [Action.SceneTrigger, 6, 2],
  [Action.SceneTrigger, 7, 2],
  [Action.SceneTrigger, 8, 2],
  [Action.SceneTrigger, 9, 2],
];